# Generated by Django 5.1 on 2024-09-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_uid', models.IntegerField(default='001')),
                ('current_uid', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'bliss_guest_user',
            },
        ),
    ]
