# Generated by Django 5.1 on 2024-09-07 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0002_guestuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuestUser',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='guest_id',
        ),
    ]
