# Generated by Django 5.1 on 2024-08-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0006_alter_cart_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('display_value', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('role_cat', models.CharField(blank=True, max_length=30, null=True)),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'biz_role',
            },
        ),
    ]
