# Generated by Django 5.1 on 2024-08-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0007_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='users', to='biz.role'),
        ),
    ]
