# Generated by Django 5.1 on 2024-08-27 07:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0008_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
