# Generated by Django 5.1 on 2024-09-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0009_alter_product_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(db_index=True, max_length=150, null=True)),
                ('mobile_number', models.CharField(db_index=True, max_length=10, null=True)),
                ('message', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bliss_contact_submission',
            },
        ),
    ]
